#!/usr/bin/env bash
# open-mpm — AI agent orchestration harness
# Wrapper script: auto-generated by scripts/install-wrapper.sh / make install.
# Loads .env.local from the project root and passes all args to the binary.
# Supports --llm-skills flag (sets OPEN_MPM_SKILL_LLM=1).

set -eo pipefail

OPEN_MPM_PROJECT="__PROJECT_DIR__"
OPEN_MPM_BINARY="${OPEN_MPM_PROJECT}/target/release/open-mpm"

if [[ ! -x "${OPEN_MPM_BINARY}" ]]; then
  echo "open-mpm: binary not found at ${OPEN_MPM_BINARY}" >&2
  echo "Run: cd ${OPEN_MPM_PROJECT} && cargo build --release" >&2
  exit 1
fi

# Load API keys from project .env.local if present.
# Parse line-by-line to skip malformed entries gracefully.
if [[ -f "${OPEN_MPM_PROJECT}/.env.local" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue
    if [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
      export "$line" 2>/dev/null || true
    fi
  done < "${OPEN_MPM_PROJECT}/.env.local"
fi

# Convenience: --llm-skills flag enables LLM-based skill selection
ARGS=()
for arg in "$@"; do
  if [[ "$arg" == "--llm-skills" ]]; then
    export OPEN_MPM_SKILL_LLM=1
  else
    ARGS+=("$arg")
  fi
done

exec "${OPEN_MPM_BINARY}" "${ARGS[@]+"${ARGS[@]}"}"
